<?php

use Biller\PrestaShop\Bootstrap;

class BillerWebhooksModuleFrontController extends ModuleFrontController {

    public function __construct()
    {
        parent::__construct();

        Bootstrap::init();
    }

    public function postProcess()
    {
        parent::postProcess(); // TODO: Change the autogenerated stub
    }

    /**
     * Assign variables to smarty
     *
     * @return void
     */
    public function initContent()
    {
        parent::initContent(); // TODO: Change the autogenerated stub
    }

    /**
     * Sets controller CSS and JS files.
     *
     * @return bool
     */
    public function setMedia()
    {
        return parent::setMedia(); // TODO: Change the autogenerated stub
    }
}
